repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-mod-tidy
      - id: go-vet

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude_types:
          - markdown
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
